version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    working_directory: ~/team-239-product
    docker:
      - image: circleci/node:12.13.1
        environment:
          NODE_ENV: test
          DATABASE_URL_TEST: postgresql://postgres@localhost/circle_test
      - image: circleci/postgres:11

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test